using System;

namespace Day7
{
    internal class Program
    {
        static void Main(string[] args)
        {
            #region Part 01

            #region Problem 1

            //Car c1 = new Car();
            //Car c2 = new Car(2);
            //Car c3 = new Car(3, "BMW");
            //Car c4 = new Car(4, "BYD", 1000);

            //Console.WriteLine($"Car 1: {c1}");
            //Console.WriteLine($"Car 2: {c2}");
            //Console.WriteLine($"Car 3: {c3}");
            //Console.WriteLine($"Car 4: {c4}");

            //// Question: Why does defining a custom constructor suppress the default constructor in C#?
            //// C# only provide a default constructor if no other constructors are defined.
            //// Once you define a custom constructor, the default constructor is not automatically generated by the compiler.

            #endregion

            #region Problem 2

            //Calculator c = new Calculator();

            //Console.WriteLine($"Sum of two integers: {c.Sum(1, 2)}");
            //Console.WriteLine($"Sum of three integers: {c.Sum(1, 2, 3)}");
            //Console.WriteLine($"Sum of two doubles: {c.Sum(1.5, 2)}");

            //// Question: How does method overloading improve code readability and reusability?
            //// improve readability and reusability because it allows you to use the same method name for different operations,
            //// making it easier to understand the code.
            #endregion

            #region Problem 3

            //Child c = new Child(10, 20, 30);

            //Console.WriteLine($"X = {c.X}, Y = {c.Y}, Z = {c.Z}");

            //// Question: What is the purpose of constructor chaining in inheritance?

            //// ensure that the base class is correctly intialized before the derived class adds its oww initlaization logic
            //// It promotes code reuse and maintainability by allowing the derived class to avoid duplicating the initialization code of the base class

            #endregion

            #region Problem 4

            //Parent p1 = new Child(10, 20, 30);

            //Console.WriteLine($"Product of p1: {p1.Product()}");
            //// with override, res: 600; 
            //// with new : res: 200;

            //// Question: How does new differ from override in method overriding?
            //// new avoid polymorphism and used to hide the base class method
            //// override is used to override the base class method and enable polymorphism.

            #endregion

            #region Problem 5

            //Parent p1 = new Parent(10, 20);
            //Child c1 = new Child(10, 20, 30);

            //Console.WriteLine($"Parent: {p1}");
            //Console.WriteLine($"Child: {c1}");

            //// Question: Why is ToString() often overridden in custom classes?
            //// to provide meaningful string represenation of the object or in cw method to display
            //// it as you want, instead of the default which is the class name.

            #endregion

            #region Problem 6

            //IShape s1 = new Rectangle(10, 20);

            //s1.Draw();

            //Console.WriteLine($"Area of the Rectangle: {s1.Area}");

            //// Question: Why can't you create an instance of an interface directly?
            //// Interfaces are abstract contracts
            //// does not provide any implementation
            //// You must provide a concrete implementation
            //// it enables polymorphism

            #endregion

            #region Problem 7

            //IShape s2 = new Circle(5);

            //s2.PrintDetails();

            //// Question: What are the benefits of default implementations in interfaces introduced in C# 8.0?
            //// Code reuse, polymorphism remains
            //// you can add new methods to the interface without breaking existing implementations of the other classes

            #endregion

            #region Problem 8

            //IMovable m1 = new Car(1, "Toyota", 2000);
            //m1.Move();

            //// Question: Why is it useful to use an interface reference to access implementing class methods?
            //// to allow polymorphism and runtime flexibility, you can use the interface reference to
            //// access the methods of the implementing class without knowing the specific type of the class at compile time.
            //// code depends on interface not concrete classes
            #endregion

            #region Problem 9

            //File file = new File("Myfile.txt");

            //file.Read();
            //file.Write();

            //Console.WriteLine("Using interface:");
            //IReadable r = file;
            //IWritable w = file;
            //r.Read();
            //w.Write();

            //// Question: How does C# overcome the limitation of single inheritance with interfaces?
            //// a class can implement multiple interfaces, allowing it to inherit behavior from multiple sources,
            //// while still maintaining a clear and organized class hierarchy.
            //// avoids the diamond problem

            #endregion

            #region Problem 10

            //Shape rec = new RectangleS(10, 20);
            //rec.Draw();

            //Console.WriteLine($"Area of the Rectangle: {rec.CalculateArea()}");

            //// Question: What is the difference between a virtual method and an abstract method in C#?
            //// Virtual can have code while abstract cannot.
            //// virtual not require override, while abstract require override in derived class.


            #endregion

            #endregion

            #region Part 02

            // 1. What is the difference between class and struct in C#?

            // Class is reference type, struct is value type.
            // Class can have inheritance, struct cannot.
            // Class stored in heap, struct stored in stack.
            // Class passed by reference, struct passed by value.

            // 2. If inheritance is relation between classes clarify other relations between classes

            // Association: One class uses another class
            // Aggregation: Weak ownership
            // Composition: Strong ownership
            // Interface implementation: A class implements an interface

            // has-a : Association, Aggregation, Composition 
            // can-do: Interface implementation


            #endregion

            #region Part 03 (Bonus)

            // What is the difference between static and dynamic binding ?

            // Static binding:
            // The method call is resolved at compile time.
            // The compiler knows exactly which method to call based on the reference type.
            // Happens for non-virtual methods by default.

            // Dynamic binding:
            // The method call is resolved at runtime based on the actual object type.
            // Happens for virtual/abstract/overridden methods.
            // Enables runtime polymorphism.

            #endregion

        }
    }
}
